### ISSUE TITLE
layer ordering

### ISSUE THREAD

**Issue by calvinmetcalf** [AppGeo/maplarge#1]
the layer ordering is strictly based on when it was added to the map, so in chrome there are issues when you initialize zoomed out with the contraflow and then zoom in adding lines, thinking of the best way to do this that doesn't screw with other layers you might have...

**Comment by calvinmetcalf** [comment]
we could add a zindex type thing that would wort only among layers that were maplarge layers, thoughs @knownasilya ?

**Comment by knownasilya** [comment]
Sounds fine to me.
