### ISSUE TITLE
Replace Node.js specific EventEmitter logic with to allow for browser use without polyfill

### ISSUE THREAD

**Issue by rossjs** [AppGeo/maplarge#25]
@calvinmetcalf  Since this is meant to be used in a browser, this library shouldn't force you to polyfill Node.js native modules. The Node.js EventEmitter should be replaced with one of the several npm libraries available that work in both Node.js and browser environments.

**Comment by calvinmetcalf** [comment]
also querystring, also querystring in a dependency, also we actually inherit from event emitter so replacing it would probably be a breaking change and we actually care about that unlike Webpack that made my perfectly functional code break.

**Comment by rossjs** [comment]
Closing this out since I believe this was implemented
